language: ruby

addons:
  apt:
    packages:
      # https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
      - docker-ce

services:
- docker

# We expect RAILS_ENV to start off unset, then adjust its value as
# necessary.
before_script:
  - unset RAILS_ENV

cache:
  bundler: true
  directories:
    - $HOME/docker

before_install:
  # see https://blog.travis-ci.com/docker-rate-limits 
  # and also https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/
  # if we do not use authorized account, 
  # the pulls-per-IP quota is shared with other Travis users
  - >
    if [ ! -z "$DOCKERHUB_PASSWORD" ] && [ ! -z "$DOCKERHUB_USERNAME" ]; then
      echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin  ;
    fi

 
# GEM_ALTERNATIVE_NAME only needed for deployment 
jobs:
  include:
  - stage: test
    script:
    - mkdir tmp
    - GEM_ALTERNATIVE_NAME='' bundle exec rake test

    
before_deploy:
  - |
    nvm install --lts \
      && nvm use --lts \
      && npm i -g \
        semantic-release \
        @semantic-release/git \
        @semantic-release/changelog \
        semantic-release-rubygem

deploy:
  - provider: script
    script: ./release.sh
    on:
      branch: master
