language: ruby

addons:
  apt:
    packages:
      # https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
      - docker-ce

services:
- docker

# We expect RAILS_ENV to start off unset, then adjust its value as
# necessary.
before_script:
  - unset RAILS_ENV
  
jobs:
  include:
  - stage: test
    script:
    - mkdir tmp
    - bundle exec rake test
    
