language: ruby

addons:
  apt:
    packages:
      # https://docs.travis-ci.com/user/docker/#installing-a-newer-docker-version
      - docker-ce

services:
- docker

# We expect RAILS_ENV to start off unset, then adjust its value as
# necessary.
before_script:
  - unset RAILS_ENV
  
jobs:
  include:
  - stage: minitest
    script:
    - mkdir tmp
    - bundle exec rake minitest
    
  - stage: base
    script:
    - bundle exec rake build:base:2.5
  - stage: base
    script:
    - bundle exec rake build:base:2.6
      
  - stage: spec
    script:
    - bundle exec rake spec:2.5
  - stage: spec
    script:
    - bundle exec rake spec:2.6
    
